apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-check-app
  template:
    metadata:
      labels:
        app: health-check-app
    spec:
      containers:
      - name: health-check-container
        image: littleconsumer/my-health-check-app:latest
        ports:
        - containerPort: 8080  #app litsens on this port
