name: Deployment

on:
  push:
    branches:
      - KubeFiles
  workflow_dispatch:  ## Manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kubefiles branch
        uses: actions/checkout@v4
        with:
          ref: KubeFiles
          
      - name: List files in directory
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest

      - name: Deploy to Kubernetes
        run: |
          mkdir -p $HOME/.kube
          cd $GITHUB_WORKSPACE  # Navigate to the GitHub workspace directory

          # Create the kubeconfig file
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          
          # Ensure proper permissions
          chmod 600 $HOME/.kube/config
          echo "MARK PERMISSION"
          (cd $GITHUB_WORKSPACE; pwd; ls -lrt)
          
          export KUBECONFIG=$HOME/.kube/config
          
          # Debugging output
          echo "Kubeconfig file:"
          cat $HOME/.kube/config
          echo "Listing kubeconfig directory:"
          ls -la $HOME/.kube
          
          # Apply Kubernetes configurations
          kubectl apply -f healthCheckDeploy.yaml --validate=false
          kubectl apply -f healthCheckDeploy-service.yaml
