name: DEPLOYing to Kubernetes

on:
  push:
    branches:
      - KubeFiles
  workflow_dispatch: ## Manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:   # <--- Indentation fixed here
      - name: Checkout kubefiles branch
        uses: actions/checkout@v4
        with:
          ref: KubeFiles
      - name: List files in directory
        run: ls -la
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest
          echo "${{ secrets.KUBECONFIG }}" 
      
      - name: Deploy to Kubernetes
        run: |
         mkdir -p $HOME/.kube
         cp -p certs/* config  $HOME/.kube/.
         #echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
         #export KUBECONFIG=$HOME/.kube/config
         ls -lrt $HOME/.kube/*
         kubectl apply -f healthCheckDeploy.yaml --validate=false

