name: DEPLOYing to Kubernetes

on:
  push:
    branches:
      - kubeFiles
  workflow_dispatch: ## Manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

      - name: Checkout kubefiles branch
        uses: actions/checkout@v4
        with:
          ref: kubeFiles
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest
      
      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f kubernetes/healthCheckDeploy.yaml
