name: Deploy to Kubernetes

on:
  push:
    branches:
      - kubefiles
  workflow_dispatch: ## Manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          # Replace "/custom/path/to/git" with the actual path to the Git executable
          export PATH="'/c/Program\ Files/Git/bin':$PATH"

      - name: Check Git version
        run: |
          # Replace "/custom/path/to/git" with the actual path to the Git executable
          /c/Program\ Files/Git/bin/git --version
          
      - name: Checkout kubefiles branch
        uses: actions/checkout@v2
        with:
          ref: kubefiles
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/healthCheckDeploy.yaml
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
