name: DEPLOYing to Kubernetes

on:
  push:
    branches:
      - kubefiles
  workflow_dispatch: ## Manual trigger

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
           git config --global user.email "reachpratr@gmail.com"
           git config --global user.name "reachpratr"
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
           ls ~/.git-credentials


      - name: Set up Git
        run: |
          uname -a
          which git
          git --version
          export PATH="/usr/bin/:$PATH"

      - name: Check Git version
        run: |
          echo $PATH
            
      - name: Checkout kubefiles branch
        uses: actions/checkout@v4
        with:
          ref: kubefiles
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-health-check-app:latest
      
      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$HOME/.kube/config
          kubectl apply -f kubernetes/healthCheckDeploy.yaml
